### ISSUE TITLE
allow arguments in saved filters [$50 awarded]

### ISSUE THREAD

**Issue by vapniks** [vapniks/gnus-summary-ext#1]
Would be good if the saved filters could accept arguments.
This means that `gnus-summary-ext-saved-filters` would have to change so that each item is a list with 3 components: the name (a symbol), the arglist, the filter expression (which can now contain arguments in the arglist). 
Also `gnus-summary-ext-limit-filter` would need to be changed: 
 1) the history argument for the call to `read-from-minibuffer` in the `interactive` form now needs to also display the arguments (or default values) to saved filters
 2) the macro expansion at the end of the cl-flet\* needs to now also expand the arguments for the saved filters

It may be necessary to also require default values for arguments to be stored in `gnus-summary-ext-saved-filters` so perhaps in the defcustom form we need to have a repeat item for arguments each of which has 2 components - the argument name and the default value. Alternatively we could just use nil as the default and handle default values in the filter code itself (though that would make writing filters awkward).
##

**Comment by Malabarba** [comment]
The PR in #2 implements this feature. The default values are specified in the filter configuration, and these are used if the filter is used without arguments during an interactive call. 

Do let me know if you like the PR.

**Comment by vapniks** [comment]
Great thanks! seems to work fine. The bounty is yours (once I've figured out how to assign it to you).
Keep your eyes peeled for some more bounties like this..

**Comment by vapniks** [comment]
OK, so it seems you need to claim the bounty first (assuming you've signed up to bountysource.com).
Then I can accept the claim.

**Comment by Malabarba** [comment]
Great, it was quite fun!

I've claimed the bounty there, under the name Malabarba.

**Comment by Malabarba** [comment]
And BTW, Feel free to ping me on github if you open other bounties.

**Comment by vapniks** [comment]
bountysource seem to be a bit slow, I still haven't received any notification of your claim.

**Comment by Malabarba** [comment]
Maybe they're just a bit slow. Let's wait another day.

**Comment by vapniks** [comment]
You should have it now.

**Comment by Malabarba** [comment]
Yes, I do. :+1:
